#ifndef __CONSTANTS_H
#define __CONSTANTS_H

#define TOTAL_ACTIVE_MESSAGES   1024
#define TOTAL_CIRCULAR_NODES    TOTAL_ACTIVE_MESSAGES
#define MESSAGE_LENGTH_BYTES    512
#define TOTAL_ACTIVE_CLIENTS    100

#define SHARED_MEMORY_FILE      "536-shm"
#define SHARED_MEMORY_PROJ_ID   'Q'

#endif
